/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { Ticket } from "./Ticket";
export type { Tournament } from "./Tournament";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { Ticket__factory } from "./factories/Ticket__factory";
export { Tournament__factory } from "./factories/Tournament__factory";
